
// MARK: this file creates a data model that stores all diabetes details of the registered user.
// this data model is called across all diabetes details pages (DetailsPage and DoctorInfo)

import SwiftUI

class DiabetesDetailsData: ObservableObject {
    
    // unique user ID for each user generated by the backend, when new user registers
    @Published var userID: String = "81f3a03f-2009-4323-8a92-eeba977e784c"
    
    // diabetes details data
    @Published var diabetesType: String = "Type I" // the default type from drop-down menu
    @Published var diagnoseDate: Date = Date()
    // list of diabetes types for drop-down picker
    let diabetesTypes = ["Type I","Type II","Gestational Diabetes","Other"]
    
    // insulin details data
    @Published var insulinType: String = "Rapid-acting" // default
    @Published var adminRoute: String = "Injection" // default
    // list of insulin types for picker
    let insulinTypes = ["Rapid-acting","Short-acting", "Intermediate-acting","Long-acting","I'm not taking insulin"]
    // list of insulin administration routes for picker
    let adminRoutes = ["Injection","Pen","Pump","Other","I'm not taking insulin"]
    
    // user's other conditions and medication
    @Published var condition: String = ""
    @Published var medication: String = ""
    
    // blood sugar target range, hypo and hyper (lower and upper bound)
    @Published var lowerBound: Float = 0.0
    @Published var upperBound: Float = 0.0 // initial values of the picker are 0.0
    
    // user's doctor's name and email
    @Published var doctorName: String = ""
    @Published var doctorEmail: String = ""
    
    // boolean variable associated with clicking "All done" button
    // sending everything to backend database when button is clicked, and var value becomes "true"
    @Published var allDone: Bool = false
}
